### ISSUE TITLE
maze.cpp and n_queen.cpp causes memory leak

### ISSUE THREAD

**Issue by vierofernando** [CesiumLabs/code-examples#298]
maze.cpp allocates two nested arrays with the `new` keyword. which means they are both dynamic pointers which won't be deleted when the program exits unless a `delete` keyword is used or if it's called with a `free()` function.

the program does not delete the two nested arrays before exiting, thus, causing a memory leak when it goes out of scope.

**Comment by vierofernando** [comment]
same issue too with n_queen.cpp, line 77

**Comment by rhygg** [comment]
Inactive issue, closing.
